const enemigos = {
  0: {
    name: "Orco Salvaje",
    nivel: 3,
    maxHealth: 100,
    attack: 10,
    defense: 5,
    speed: 12,
    elementalAttribute: "Nature",
    luck: 8,
  },
  1: {
    name: "Enano Furioso",
    nivel: 5,
    maxHealth: 120,
    attack: 12,
    defense: 7,
    speed: 10,
    elementalAttribute: "Earth",
    luck: 5,
  },
  2: {
    name: "Humano Guerrero",
    nivel: 4,
    maxHealth: 110,
    attack: 15,
    defense: 8,
    speed: 9,
    elementalAttribute: "None",
    luck: 10,
  },
  3: {
    name: "Elfo Oscuro Acechador",
    nivel: 6,
    maxHealth: 90,
    attack: 18,
    defense: 6,
    speed: 14,
    elementalAttribute: "Shadow",
    luck: 6,
  },
  4: {
    name: "Troll Gigante",
    nivel: 7,
    maxHealth: 150,
    attack: 12,
    defense: 10,
    speed: 4,
    elementalAttribute: "Nature",
    luck: 2,
  },
  5: {
    name: "Goblin Astuto",
    nivel: 2,
    maxHealth: 80,
    attack: 7,
    defense: 3,
    speed: 16,
    elementalAttribute: "None",
    luck: 4,
  },
  6: {
    name: "Vampiro Sanguinario",
    nivel: 8,
    maxHealth: 140,
    attack: 15,
    defense: 6,
    speed: 8,
    elementalAttribute: "Darkness",
    luck: 9,
  },
  7: {
    name: "Sirena Encantadora",
    nivel: 5,
    maxHealth: 95,
    attack: 10,
    defense: 4,
    speed: 18,
    elementalAttribute: "Water",
    luck: 7,
  },
};
